package frc.robot.turret;

public enum TurretState {
  STOW,
  ALLOW_EXTERNAL_CONTROL,
  ALLOW_EXTERNAL_CONTROL_FACING_HUB,
  FACE_HUB,
  TARGET_HUB,
  PASS,
  PASS_FAR,
  PASS_SOTM,
  TARGET_HUB_FROM_POSE;
}
