package frc.lib.vision;


import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.units.measure.Time;

import static edu.wpi.first.units.Units.Seconds;

/**
 * A pose estimate generated by a vision-based pose estimation system.
 *
 * @param pose The pose.
 * @param timestamp The time when the pose estimated.
 */
public record VisionPoseEstimate(Pose3d pose, Time timestamp) {

    public static VisionPoseEstimate fromLimelightPoseEstimate(LimelightHelpers.PoseEstimate poseEstimate) {
        return new VisionPoseEstimate(new Pose3d(poseEstimate.pose), Seconds.of(poseEstimate.timestampSeconds));
    }

}
